[build-system]
requires = ["hatchling>=1.11.0"]
build-backend = "hatchling.build"


[project]
requires-python = ">=3.8"
version = "0.0.1"

name        = "storyteller"
description = ""
readme      = "README.md"
license     = "MIT"

dependencies = [
"transformers",
"diffusers",
"accelerate",
"TTS",
]

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
  "isort",
]

[tool.isort]
profile = "black"
force_sort_within_sections = true
